import React from 'react';
import { motion } from 'framer-motion';
import { 
  Building2, 
  History, 
  Wallet, 
  CreditCard, 
  User, 
  TrendingUp, 
  Flag,
  CheckCircle2
} from 'lucide-react';

const EligibilityListWithBackground = () => {
  // Data structure remains the same
  const criteriaData = [
    {
      title: "Business Type",
      description: "Registered MSME/SME engaged in manufacturing, trading, or services.",
      highlight: "MSME / SME",
      icon: <Building2 className="w-5 h-5" />,
      // Adjusted colors slightly to pop better on dark backgrounds
      color: "text-blue-400", 
      bgColor: "bg-blue-500/10",
      borderColor: "border-blue-500/20"
    },
    {
      title: "Business Vintage",
      description: "Operational history required to establish stability.",
      highlight: "2–3 Years",
      icon: <History className="w-5 h-5" />,
      color: "text-purple-400",
      bgColor: "bg-purple-500/10",
      borderColor: "border-purple-500/20"
    },
    {
      title: "Annual Turnover",
      description: "Minimum annual revenue generated by the business.",
      highlight: "₹20–40 Lakh",
      icon: <Wallet className="w-5 h-5" />,
      color: "text-green-400",
      bgColor: "bg-green-500/10",
      borderColor: "border-green-500/20"
    },
    {
      title: "Credit Score",
      description: "CIBIL/Credit score requirement for the primary applicant.",
      highlight: "650 – 700+",
      icon: <CreditCard className="w-5 h-5" />,
      color: "text-rose-400",
      bgColor: "bg-rose-500/10",
      borderColor: "border-rose-500/20"
    },
    {
      title: "Applicant Age",
      description: "Age bracket for the primary business owner.",
      highlight: "21 – 65 Years",
      icon: <User className="w-5 h-5" />,
      color: "text-amber-400",
      bgColor: "bg-amber-500/10",
      borderColor: "border-amber-500/20"
    },
    {
      title: "Profitability",
      description: "Consistent profit record (exceptions for startups).",
      highlight: "Min 2 Years",
      icon: <TrendingUp className="w-5 h-5" />,
      color: "text-teal-400",
      bgColor: "bg-teal-500/10",
      borderColor: "border-teal-500/20"
    },
    {
      title: "Citizenship",
      description: "Nationality requirement for the business owner.",
      highlight: "Indian Resident",
      icon: <Flag className="w-5 h-5" />,
      color: "text-indigo-400",
      bgColor: "bg-indigo-500/10",
      borderColor: "border-indigo-500/20"
    }
  ];

  return (
    // Main section now has relative positioning to hold the absolute background image
    <section className="relative py-24 px-4 sm:px-6 lg:px-8 overflow-hidden bg-slate-900">
      
      {/* BACKGROUND IMAGE AREA START */}
      <div className="absolute inset-0 z-0">
        {/* Replace 'src' with your actual image URL. Using a placeholder city view here. */}
        <img 
            src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070" 
            alt="Modern business background" 
            className="w-full h-full object-cover scale-105"
        />
        {/* Strong dark overlay to ensure text readability */}
        <div className="absolute inset-0 bg-gradient-to-b from-slate-900/95 via-slate-900/80 to-slate-900/95 backdrop-blur-[2px]"></div>
      </div>
      {/* BACKGROUND IMAGE AREA END */}


      {/* Content Container - z-10 places it above the background image */}
      <div className="relative z-10 max-w-3xl mx-auto">
        
        {/* Header - Updated for dark mode contrast */}
        <div className="mb-12 border-l-4 border-indigo-500 pl-6">
          <motion.h2 
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="text-3xl font-bold text-white"
          >
            Eligibility Checklist
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="mt-2 text-slate-300 text-lg"
          >
            Quickly check if your business qualifies.
          </motion.p>
        </div>

        {/* List Layout Container */}
        <div className="relative">
          {/* Timeline line made subtler for dark background */}
          <div className="absolute left-8 top-4 bottom-4 w-px bg-slate-700/50 hidden sm:block" />

          <motion.div 
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-50px" }}
            variants={{
              visible: { transition: { staggerChildren: 0.08 } }
            }}
            className="space-y-4"
          >
            {criteriaData.map((item, index) => (
              <motion.div
                key={index}
                variants={{
                  hidden: { opacity: 0, y: 20 }, // Changed to Y axis movement for this style
                  visible: { opacity: 1, y: 0 }
                }}
                // Glassmorphism card style: translucent dark bg with blur and subtle border
                className="group relative bg-slate-800/50 backdrop-blur-md rounded-xl transition-all duration-300 hover:bg-slate-800/70 border border-slate-700/50 hover:border-slate-600 p-4 sm:p-5"
              >
                <div className="flex flex-col sm:flex-row sm:items-center gap-4 sm:gap-6 relative z-10">
                  
                  {/* Icon Column */}
                  <div className="flex-shrink-0">
                    <motion.div 
                      whileHover={{ scale: 1.1, rotate: 5 }}
                      // Updated rings to match dark theme
                      className={`w-12 h-12 rounded-full flex items-center justify-center ${item.bgColor} ${item.color} shadow-sm ring-2 ring-slate-700/50 group-hover:ring-slate-600 transition-all`}
                    >
                      {item.icon}
                    </motion.div>
                  </div>

                  {/* Text Column */}
                  <div className="flex-grow min-w-0">
                    <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                      <div>
                        {/* Text colors updated for dark mode */}
                        <h3 className="text-lg font-semibold text-slate-100 group-hover:text-white transition-colors">
                          {item.title}
                        </h3>
                        <p className="text-slate-400 text-sm mt-0.5 pr-4">
                          {item.description}
                        </p>
                      </div>
                      
                      {/* Highlight Badge */}
                      <div className="flex-shrink-0 mt-2 sm:mt-0">
                        {/* Using border-color property from data for subtle outline */}
                        <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-bold border ${item.borderColor} ${item.bgColor} ${item.color} backdrop-blur-sm`}>
                          {item.highlight}
                        </span>
                      </div>
                    </div>
                  </div>


                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>

      </div>
    </section>
  );
};

export default EligibilityListWithBackground;